create table if not exists users
(
	id bigint generated by default as identity
		constraint users_pkey
			primary key,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	password varchar(255) not null,
	username varchar(255) not null
);

create table if not exists admins
(
	admin_id serial,
	id bigint not null
		constraint admins_pkey
			primary key
		constraint user_admin_fkey
			references users
);

create table if not exists customers
(
	address varchar(255),
	phone_number varchar(255),
	id bigint not null
		constraint customers_pkey
			primary key
		constraint user_customer_fkey
			references users
);

create table if not exists workers
(
	role varchar(255),
	id bigint not null
		constraint workers_pkey
			primary key
		constraint user_worker_fkey
			references users
);

create table if not exists bookings
(
	booking_id integer not null
		constraint bookings_pkey
			primary key,
	end_time timestamp,
	start_time timestamp,
	user_id bigint
		constraint user_booking_fkey
			references customers,
	worker_id bigint
		constraint worker_booking_fkey
			references workers
);

create table working_hours
(
	entry_id integer not null
		constraint working_hours_pkey
			primary key,
	end_time timestamp,
	start_time timestamp,
	worker_id bigint
		constraint worker_hours_fkey
			references workers
);

-- TODO: Check if this is needed or not.

create table user_entity_roles
(
	user_entity_id bigint not null
		constraint user_role_fkey
			references users,
	roles varchar(255)
);
