# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: sept-backend  
spec:
  selector:
    app: sept
    tier: backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sept-backend
  labels: 
    app: sept
    tier: backend
spec:
  replicas: 2    
  selector:
    matchLabels: 
      app: sept
      tier: backend
  template:
    metadata:
      labels: 
        app: sept
        tier: backend  
    spec:                 
      containers: 
      - name: sept-backend 
        image: sept/backend
        imagePullPolicy: Never
        env:   
          - name: JAVA_OPTS
            value: -Dspring.profiles.active=deploy -Dspring.datasource.url=jdbc:postgresql://postgres:5432/sept-main
          - name: DB_HOST   
            valueFrom: 
              configMapKeyRef:
                name: db-config  
                key: host
          - name: DB_NAME 
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password     
        ports:
        - containerPort: 8080