# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: postgres  # DNS name 
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector: 
    app: postgres
    tier: database
  clusterIP: None  

---

# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  selector: 
    matchLabels:
      app: postgres
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
      - image: postgres:latest
        imagePullPolicy: "IfNotPresent"
        name: postgres 
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: username
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: name
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:        
        - name: postgres-persistent-storage
          mountPath: /var/lib/mysql
        - name: postgres-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-initdbdata
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-initdb
        configMap:
          name: initdb
      - name: postgres-initdbdata
        configMap:
          name: initdbdata
      - name: postgres-persistent-storage 
        persistentVolumeClaim:
          claimName: postgres-pv-claim