# Define 'Service' to expose FrontEnd Application
apiVersion: v1
kind: Service
metadata:
  name: sept-frontend
spec:
  selector: # pod labels should match these
    app: sept
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer 

---

# 'Deployment' to manage of configuration of frontEnd Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sept-frontend
  labels: 
    app: sept
    tier: frontend
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: sept
      tier: frontend
  template:
    metadata:
      labels:
        app: sept
        tier: frontend  
    spec:                 
      containers: 
      - name: sept-frontend
        image: sept/frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000