version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lemongrab
      POSTGRES_PASSWORD: adom
      POSTGRES_DB: sept-main
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  backend:
    container_name: sept-backend
    image: sept/backend
    restart: always
    depends_on:
      - postgres-db
    ports:
    - "8080:8080"