version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lemongrab
      POSTGRES_PASSWORD: adom
      POSTGRES_DB: sept-main
    volumes:
      - ./../BackEnd/scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./../BackEnd/scripts/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  backend:
    container_name: sept-backend
    image: sept/backend
    restart: always
    depends_on:
      - postgres-db
    ports:
    - "8080:8080"
    environment:
    - JAVA_OPTS="-Dspring.profiles.active=deploy"
  frontend:
    container_name: sept-frontend
    depends_on:
      - backend
    build:
      context: ../FrontEnd
      dockerfile: Dockerfile
    volumes:
      - ".:/FrontEnd/app"
      - "./FrontEnd/app/node_modules"
    ports:
      - 3001:3000
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
