# release-flow.yaml
# On change to release, run unit tests and make 
# pull request on master branch.
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:

  job-1:
    name: FrontEnd Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FrontEnd
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test

  job-2:
    name: BackEnd Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BackEnd
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=dev

  job-3:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    steps:
    - name: Create Pull Request using REST API
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/pulls \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Accept: application/vnd.github.v3+json' \
        --data '{
          "title":"Staged & Ready!",
          "body": "This pull request was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
          "head":"release",
          "base":"master"
          }' 
